name: Node tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting Up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
        env:
          CI: true